### ISSUE TITLE
API Listado Documentos Emitidos no retorna datos

### ISSUE THREAD

**Issue by ntapian** [LibreDTE/libredte-app-community#28]
El API Listado de Documentos Emitidos no retorna datos.

Al probarla en Postman con los parámetros rut emisor no retorna datos.

"No se encontraron documentos emitidos que coincidan con la búsqueda" es lo único que se obtiene.

**Comment by estebandelaf** [comment]
@ntapian si obtienes ese mensaje es porque no hay datos para los filtros usados. Recomiendo revisar los filtros.
