### ISSUE TITLE
Resolution 66 SII

### ISSUE THREAD

**Issue by tejesoft1** [LibreDTE/libredte-app-community#31]
No se pueden generar DTE cumpliendo con la Resolución Exenta SII N°66 del 02 de agosto de 2022 

EMISIÓN DE DOCUMENTOS TRIBUTARIOS ELECTRÓNICOS EN OPERACIONES DE COMPRA Y VENTA DE MONEDA EXTRANJERA.

SANTIAGO, 02 DE AGOSTO DE 2022 RESOLUCIÓN EX. SII N° 66.-  
https://www.sii.cl/normativa_legislacion/resoluciones/2022/reso66.pdf

**Comment by estebandelaf** [comment]
@tejesoft1 efectivamente, por el momento no es una funcionalidad disponible. Quizás en la siguiente versión que publicaré lo incluya (en octubre) pero no es seguro ya que estoy viendo otras prioridades en el proyecto, y sobre todo en la Edición Enterprise.
