### ISSUE TITLE
Manual de instalación libredte-webapp

### ISSUE THREAD

**Issue by dexv** [LibreDTE/libredte-app-community#32]
Hola,

Recuerdo haber utilizado un manual de instalación, pero ahora no lo encuentro ¿Sigue disponible?

Saludos

**Comment by estebandelaf** [comment]
@dexv en la fecha consultada no había manual. Y actualmente estoy migrando a una nueva versión del framework por lo que la instalación cambiará (será muuuucho más fácil). Sin embargo, no pretendo tener eso publicado completo (o detallado) antes de septiembre, y probablemente lo deje para el cumpleaños 9 el 1ero de octubre.
